[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_22"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
